<?php
/**
 * Noey_Children_Service — Parent ↔ Child account management.
 *
 * v2.1 changes:
 *  - create_child()    — nickname is the user_login (Caribbean leaderboard name)
 *                        first_name/last_name stored on WP user
 *                        display_name = first_name
 *                        noey_nickname stored in user meta
 *                        email = nickname@noey.local (children never log in by email)
 *  - format_child_row() — includes nickname from noey_nickname user meta
 *  - update_child()    — accepts first_name / last_name updates
 *
 * @package NoeyAPI
 */

defined( 'ABSPATH' ) || exit;

class Noey_Children_Service {

    // ── Create ────────────────────────────────────────────────────────────────

    /**
     * Create a new child WP user and link it to the parent.
     *
     * v2.1: nickname is the Caribbean leaderboard name (e.g. TurboConch).
     * It becomes the WP user_login. Children never log in directly —
     * they are always accessed via the parent's active child selector.
     *
     * @param int   $parent_id
     * @param array $data {
     *   @type string $first_name   Required.
     *   @type string $last_name    Required.
     *   @type string $nickname     Required. Caribbean name — becomes user_login.
     *   @type string $password     Required. Auto-generated by React.
     *   @type string $standard     e.g. 'std_4'.
     *   @type string $term         e.g. 'term_1'.
     *   @type int    $age          Optional.
     *   @type int    $avatar_index 1–5 (default 1).
     * }
     * @return array|WP_Error  Child profile on success.
     */
    public static function create_child( int $parent_id, array $data ): array|WP_Error {
        Noey_Debug::log( 'children.create', 'Creating child account', [
            'parent_id'  => $parent_id,
            'first_name' => $data['first_name'] ?? '',
            'nickname'   => $data['nickname']   ?? '',
        ], $parent_id, 'info' );

        // Enforce max children
        $count = self::child_count( $parent_id );
        if ( $count >= NOEY_MAX_CHILDREN ) {
            Noey_Debug::log( 'children.create', 'Max children limit reached', [
                'parent_id' => $parent_id,
                'count'     => $count,
            ], $parent_id, 'warning' );
            return new WP_Error(
                'noey_max_children',
                'Maximum of ' . NOEY_MAX_CHILDREN . ' student profiles allowed per account.',
                [ 'status' => 422 ]
            );
        }

        // Validate required fields
        $first_name   = sanitize_text_field( $data['first_name'] ?? '' );
        $last_name    = sanitize_text_field( $data['last_name']  ?? '' );
        $nickname     = sanitize_text_field( $data['nickname']   ?? '' );  // Caribbean name = user_login
        $password     = $data['password'] ?? '';

        if ( ! $first_name || ! $last_name || ! $nickname || ! $password ) {
            return new WP_Error(
                'noey_missing_fields',
                'first_name, last_name, nickname, and password are required.',
                [ 'status' => 422 ]
            );
        }

        // Nickname is the user_login — must be unique across WP
        if ( username_exists( $nickname ) ) {
            return new WP_Error(
                'noey_nickname_taken',
                'That nickname is already in use. Please choose another.',
                [ 'status' => 409 ]
            );
        }

        // Create WP user — nickname is user_login, email is throwaway
        $throwaway_email = strtolower( $nickname ) . '@noey.local';
        $child_id        = wp_create_user( $nickname, $password, $throwaway_email );

        if ( is_wp_error( $child_id ) ) {
            Noey_Debug::log( 'children.create', 'wp_create_user failed', [
                'parent_id' => $parent_id,
                'nickname'  => $nickname,
                'error'     => $child_id->get_error_message(),
            ], $parent_id, 'error' );
            return new WP_Error( 'noey_create_failed', 'Failed to create student account.', [ 'status' => 500 ] );
        }

        // Set role and all name fields
        $child_user = new WP_User( $child_id );
        $child_user->set_role( 'noey_child' );

        wp_update_user( [
            'ID'           => $child_id,
            'first_name'   => $first_name,
            'last_name'    => $last_name,
            'display_name' => $first_name,  // Display = first name only
            'nickname'     => $nickname,    // WP nickname = Caribbean name
        ] );

        // Store parent link on child user meta
        update_user_meta( $child_id, 'noey_parent_id',    $parent_id );
        update_user_meta( $child_id, 'noey_nickname',     $nickname );   // Caribbean leaderboard identity
        update_user_meta( $child_id, 'noey_avatar_index', max( 1, min( 5, (int) ( $data['avatar_index'] ?? 1 ) ) ) );

        if ( isset( $data['age'] ) ) {
            update_user_meta( $child_id, 'noey_age', (int) $data['age'] );
        }

        // Insert relationship row
        global $wpdb;
        $wpdb->insert(
            $wpdb->prefix . 'noey_children',
            [
                'parent_id'    => $parent_id,
                'child_id'     => $child_id,
                'display_name' => $first_name,
                'standard'     => sanitize_text_field( $data['standard'] ?? '' ),
                'term'         => sanitize_text_field( $data['term']     ?? '' ),
                'age'          => isset( $data['age'] ) ? (int) $data['age'] : null,
                'avatar_index' => max( 1, min( 5, (int) ( $data['avatar_index'] ?? 1 ) ) ),
                'created_at'   => current_time( 'mysql', true ),
            ],
            [ '%d', '%d', '%s', '%s', '%s', '%d', '%d', '%s' ]
        );

        // Auto-set as active child if this is the first one
        if ( $count === 0 ) {
            update_user_meta( $parent_id, 'noey_active_child_id', $child_id );
        }

        Noey_Debug::log( 'children.create', 'Child account created', [
            'parent_id'  => $parent_id,
            'child_id'   => $child_id,
            'nickname'   => $nickname,
            'first_name' => $first_name,
        ], $parent_id, 'info' );

        return self::get_child( $child_id );
    }

    // ── Read ──────────────────────────────────────────────────────────────────

    /**
     * List all children for a parent.
     *
     * @return array[]
     */
    public static function list_children( int $parent_id ): array {
        global $wpdb;

        $rows = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_children WHERE parent_id = %d ORDER BY child_row_id ASC",
                $parent_id
            ),
            ARRAY_A
        ) ?: [];

        Noey_Debug::log( 'children.list', 'Listed children', [
            'parent_id' => $parent_id,
            'count'     => count( $rows ),
        ], $parent_id, 'debug' );

        return array_map( [ __CLASS__, 'format_child_row' ], $rows );
    }

    /**
     * Get a single child profile by child WP user ID.
     */
    public static function get_child( int $child_id ): array|WP_Error {
        global $wpdb;

        $row = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_children WHERE child_id = %d",
                $child_id
            ),
            ARRAY_A
        );

        if ( ! $row ) {
            return new WP_Error( 'noey_not_found', 'Student profile not found.', [ 'status' => 404 ] );
        }

        return self::format_child_row( $row );
    }

    /**
     * Get child by parent_id + child_id (ownership check).
     */
    public static function get_child_for_parent( int $parent_id, int $child_id ): array|WP_Error {
        global $wpdb;

        $row = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_children WHERE parent_id = %d AND child_id = %d",
                $parent_id,
                $child_id
            ),
            ARRAY_A
        );

        if ( ! $row ) {
            return new WP_Error(
                'noey_not_found',
                'Student profile not found or does not belong to this account.',
                [ 'status' => 404 ]
            );
        }

        return self::format_child_row( $row );
    }

    // ── Update ────────────────────────────────────────────────────────────────

    /**
     * Update a child's profile fields.
     *
     * v2.1: accepts first_name / last_name in addition to existing fields.
     * display_name stays in sync with first_name if first_name is updated.
     *
     * @param int   $parent_id
     * @param int   $child_id
     * @param array $data  Keys: first_name, last_name, standard, term, age, avatar_index
     */
    public static function update_child( int $parent_id, int $child_id, array $data ): array|WP_Error {
        Noey_Debug::log( 'children.update', 'Updating child profile', [
            'parent_id' => $parent_id,
            'child_id'  => $child_id,
            'fields'    => array_keys( $data ),
        ], $parent_id, 'info' );

        $existing = self::get_child_for_parent( $parent_id, $child_id );
        if ( is_wp_error( $existing ) ) {
            return $existing;
        }

        global $wpdb;
        $db_update  = [];
        $db_format  = [];
        $wp_update  = [ 'ID' => $child_id ];

        if ( isset( $data['first_name'] ) ) {
            $first_name                = sanitize_text_field( $data['first_name'] );
            $db_update['display_name'] = $first_name;
            $db_format[]               = '%s';
            $wp_update['first_name']   = $first_name;
            $wp_update['display_name'] = $first_name; // keep in sync
        }

        if ( isset( $data['last_name'] ) ) {
            $wp_update['last_name'] = sanitize_text_field( $data['last_name'] );
        }

        if ( isset( $data['standard'] ) ) {
            $db_update['standard'] = sanitize_text_field( $data['standard'] );
            $db_format[]           = '%s';
        }

        if ( isset( $data['term'] ) ) {
            $db_update['term'] = sanitize_text_field( $data['term'] );
            $db_format[]       = '%s';
        }

        if ( isset( $data['age'] ) ) {
            $db_update['age'] = (int) $data['age'];
            $db_format[]      = '%d';
        }

        if ( isset( $data['avatar_index'] ) ) {
            $db_update['avatar_index'] = max( 1, min( 5, (int) $data['avatar_index'] ) );
            $db_format[]               = '%d';
            update_user_meta( $child_id, 'noey_avatar_index', $db_update['avatar_index'] );
        }

        // Apply WP user updates if any name fields changed
        if ( count( $wp_update ) > 1 ) {
            wp_update_user( $wp_update );
        }

        // Apply DB row updates
        if ( ! empty( $db_update ) ) {
            $wpdb->update(
                $wpdb->prefix . 'noey_children',
                $db_update,
                [ 'child_id' => $child_id ],
                $db_format,
                [ '%d' ]
            );
        }

        return self::get_child( $child_id );
    }

    // ── Delete ────────────────────────────────────────────────────────────────

    /**
     * Remove a child profile and the WP user.
     */
    public static function remove_child( int $parent_id, int $child_id ): true|WP_Error {
        $existing = self::get_child_for_parent( $parent_id, $child_id );
        if ( is_wp_error( $existing ) ) {
            return $existing;
        }

        global $wpdb;

        $wpdb->delete( $wpdb->prefix . 'noey_children', [ 'child_id' => $child_id ], [ '%d' ] );

        require_once ABSPATH . 'wp-admin/includes/user.php';
        wp_delete_user( $child_id );

        $active = (int) get_user_meta( $parent_id, 'noey_active_child_id', true );
        if ( $active === $child_id ) {
            delete_user_meta( $parent_id, 'noey_active_child_id' );
        }

        Noey_Debug::log( 'children.remove', 'Child profile removed', [
            'parent_id' => $parent_id,
            'child_id'  => $child_id,
        ], $parent_id, 'info' );

        return true;
    }

    // ── Profile Switching ─────────────────────────────────────────────────────

    public static function switch_to_child( int $parent_id, int $child_id ): array|WP_Error {
        $child = self::get_child_for_parent( $parent_id, $child_id );
        if ( is_wp_error( $child ) ) {
            return $child;
        }

        update_user_meta( $parent_id, 'noey_active_child_id', $child_id );
        clean_user_cache( $parent_id );

        Noey_Debug::log( 'children.switch', 'Switched active child', [
            'parent_id' => $parent_id,
            'child_id'  => $child_id,
        ], $parent_id, 'info' );

        return [
            'active_child_id' => $child_id,
            'child'           => $child,
        ];
    }

    public static function switch_to_parent( int $parent_id ): array {
        delete_user_meta( $parent_id, 'noey_active_child_id' );

        Noey_Debug::log( 'children.switch', 'Switched to parent context', [
            'parent_id' => $parent_id,
        ], $parent_id, 'info' );

        return [ 'active_child_id' => null ];
    }

    // ── Utilities ─────────────────────────────────────────────────────────────

    public static function child_count( int $parent_id ): int {
        global $wpdb;
        return (int) $wpdb->get_var(
            $wpdb->prepare(
                "SELECT COUNT(*) FROM {$wpdb->prefix}noey_children WHERE parent_id = %d",
                $parent_id
            )
        );
    }

    public static function owns_child( int $parent_id, int $child_id ): bool {
        global $wpdb;
        return (bool) $wpdb->get_var(
            $wpdb->prepare(
                "SELECT 1 FROM {$wpdb->prefix}noey_children WHERE parent_id = %d AND child_id = %d",
                $parent_id,
                $child_id
            )
        );
    }

    // ── Formatter ─────────────────────────────────────────────────────────────

    /**
     * Format a noey_children DB row for API response.
     *
     * v2.1: includes nickname from noey_nickname user meta.
     * This is the Caribbean leaderboard identity (e.g. TurboConch).
     */
    private static function format_child_row( array $row ): array {
        $child_id = (int) $row['child_id'];

        return [
            'child_id'     => $child_id,
            'display_name' => $row['display_name'],
            'first_name'   => get_user_meta( $child_id, 'first_name', true ),
            'last_name'    => get_user_meta( $child_id, 'last_name', true ),
            'nickname'     => get_user_meta( $child_id, 'noey_nickname', true ) ?: '',
            'standard'     => $row['standard'],
            'term'         => $row['term'],
            'age'          => $row['age'] !== null ? (int) $row['age'] : null,
            'avatar_index' => (int) $row['avatar_index'],
            'created_at'   => $row['created_at'],
        ];
    }
}