<?php
/**
 * Noey_Insight_Service — AI-generated insights for exam sessions and weekly digests.
 *
 * Per-exam insight:
 *   - Generated on demand (POST /noey/v1/insights/{session_id})
 *   - Cached in wp_noey_exam_insights (one row per session, unique)
 *   - Payload built from session + answers + topic breakdown
 *
 * Weekly digest:
 *   - Generated by cron (Noey_Cron::run_weekly_digest)
 *   - Stored in wp_noey_weekly_insights (one row per child per ISO week)
 *   - Only runs for children who completed ≥1 exam in the past 7 days
 *
 * @package NoeyAPI
 */

defined( 'ABSPATH' ) || exit;

class Noey_Insight_Service {

    // ── Per-Exam Insight ──────────────────────────────────────────────────────

    /**
     * Generate (or return cached) insight for a completed exam session.
     *
     * @param  int $session_id
     * @param  int $child_id    Used to verify ownership.
     * @return array|WP_Error   { session_id, insight_text, generated_at, from_cache }
     */
    public static function get_or_generate_exam_insight( int $session_id, int $child_id ): array|WP_Error {
        Noey_Debug::log( 'insight.exam', 'Insight requested', [
            'session_id' => $session_id,
            'child_id'   => $child_id,
        ], $child_id, 'info' );

        // ── Cache check ───────────────────────────────────────────────────────
        global $wpdb;
        $cached = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_exam_insights WHERE session_id = %d AND child_id = %d",
                $session_id,
                $child_id
            ),
            ARRAY_A
        );

        if ( $cached ) {
            Noey_Debug::log( 'insight.exam', 'Cache hit — returning stored insight', [
                'session_id'   => $session_id,
                'generated_at' => $cached['generated_at'],
            ], $child_id, 'debug' );

            return [
                'session_id'   => $session_id,
                'insight_text' => $cached['insight_text'],
                'model_used'   => $cached['model_used'],
                'generated_at' => $cached['generated_at'],
                'from_cache'   => true,
            ];
        }

        // ── Build payload from DB ─────────────────────────────────────────────
        $payload = self::build_exam_payload( $session_id, $child_id );
        if ( is_wp_error( $payload ) ) {
            return $payload;
        }

        // ── Call Railway /insight endpoint ────────────────────────────────────
        $response = self::call_railway_exam_insight( $payload );
        if ( is_wp_error( $response ) ) {
            return $response;
        }

        $insight_text = sanitize_textarea_field( $response['insight'] ?? '' );
        $model_used   = sanitize_text_field( $response['model'] ?? 'unknown' );

        if ( ! $insight_text ) {
            Noey_Debug::log( 'insight.exam', 'Railway returned empty insight text', [
                'session_id' => $session_id,
                'response'   => $response,
            ], $child_id, 'error' );
            return new WP_Error( 'noey_insight_empty', 'Insight could not be generated at this time.', [ 'status' => 503 ] );
        }

        // ── Store in cache ────────────────────────────────────────────────────
        $generated_at = current_time( 'mysql', true );
        $wpdb->insert(
            $wpdb->prefix . 'noey_exam_insights',
            [
                'session_id'   => $session_id,
                'child_id'     => $child_id,
                'insight_text' => $insight_text,
                'model_used'   => $model_used,
                'generated_at' => $generated_at,
            ],
            [ '%d', '%d', '%s', '%s', '%s' ]
        );

        Noey_Debug::log( 'insight.exam', 'Insight generated and cached', [
            'session_id' => $session_id,
            'child_id'   => $child_id,
            'model_used' => $model_used,
        ], $child_id, 'info' );

        return [
            'session_id'   => $session_id,
            'insight_text' => $insight_text,
            'model_used'   => $model_used,
            'generated_at' => $generated_at,
            'from_cache'   => false,
        ];
    }

    // ── Weekly Digest ─────────────────────────────────────────────────────────

    /**
     * Generate a weekly digest insight for one child.
     * Called by Noey_Cron — skips if child had no exams this week.
     *
     * @param  int    $child_id
     * @param  string $iso_week  e.g. '2026-W12'
     * @return array|WP_Error
     */
    public static function generate_weekly_digest( int $child_id, string $iso_week ): array|WP_Error {
        Noey_Debug::log( 'insight.weekly', 'Generating weekly digest', [
            'child_id' => $child_id,
            'iso_week' => $iso_week,
        ], $child_id, 'info' );

        global $wpdb;

        // Skip if already generated this week
        $existing = $wpdb->get_var(
            $wpdb->prepare(
                "SELECT digest_id FROM {$wpdb->prefix}noey_weekly_insights WHERE child_id = %d AND iso_week = %s",
                $child_id,
                $iso_week
            )
        );

        if ( $existing ) {
            Noey_Debug::log( 'insight.weekly', 'Weekly digest already exists — skipping', [
                'child_id' => $child_id,
                'iso_week' => $iso_week,
            ], $child_id, 'debug' );
            return [ 'skipped' => true, 'reason' => 'already_generated' ];
        }

        // Build weekly payload
        $payload = self::build_weekly_payload( $child_id, $iso_week );
        if ( is_wp_error( $payload ) ) {
            return $payload;
        }

        if ( empty( $payload['period']['exams_completed'] ) ) {
            Noey_Debug::log( 'insight.weekly', 'No exams this week — skipping', [
                'child_id' => $child_id,
                'iso_week' => $iso_week,
            ], $child_id, 'debug' );
            return [ 'skipped' => true, 'reason' => 'no_exams_this_week' ];
        }

        // Call Railway /overall-insight/:child_id
        $response = self::call_railway_weekly_insight( $child_id, $payload );
        if ( is_wp_error( $response ) ) {
            return $response;
        }

        // Weekly response shape: { user_id, period, insight }
        $insight_text = sanitize_textarea_field( $response['insight'] ?? '' );
        $generated_at = current_time( 'mysql', true );

        $wpdb->insert(
            $wpdb->prefix . 'noey_weekly_insights',
            [
                'child_id'     => $child_id,
                'iso_week'     => $iso_week,
                'payload_json' => wp_json_encode( $payload ),
                'insight_text' => $insight_text,
                'generated_at' => $generated_at,
            ],
            [ '%d', '%s', '%s', '%s', '%s' ]
        );

        Noey_Debug::log( 'insight.weekly', 'Weekly digest generated', [
            'child_id'  => $child_id,
            'iso_week'  => $iso_week,
            'exams'     => $payload['period']['exams_completed'],
        ], $child_id, 'info' );

        return [
            'child_id'     => $child_id,
            'iso_week'     => $iso_week,
            'insight_text' => $insight_text,
            'generated_at' => $generated_at,
        ];
    }

    /**
     * Retrieve a stored weekly digest for a child.
     */
    public static function get_weekly_digest( int $child_id, string $iso_week ): array|WP_Error {
        global $wpdb;

        $row = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_weekly_insights WHERE child_id = %d AND iso_week = %s",
                $child_id,
                $iso_week
            ),
            ARRAY_A
        );

        if ( ! $row ) {
            return new WP_Error( 'noey_not_found', "No weekly insight found for week {$iso_week}.", [ 'status' => 404 ] );
        }

        return [
            'child_id'     => (int) $row['child_id'],
            'iso_week'     => $row['iso_week'],
            'insight_text' => $row['insight_text'],
            'generated_at' => $row['generated_at'],
        ];
    }

    // ── Payload Builders ──────────────────────────────────────────────────────

    /**
     * Build the per-exam insight payload from stored session data.
     */
    private static function build_exam_payload( int $session_id, int $child_id ): array|WP_Error {
        global $wpdb;

        $session = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_exam_sessions WHERE session_id = %d AND child_id = %d AND state = 'completed'",
                $session_id,
                $child_id
            ),
            ARRAY_A
        );

        if ( ! $session ) {
            return new WP_Error( 'noey_not_found', 'Completed exam session not found.', [ 'status' => 404 ] );
        }

        $breakdown = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT topic, correct, total, pct FROM {$wpdb->prefix}noey_topic_breakdown WHERE session_id = %d ORDER BY pct DESC",
                $session_id
            ),
            ARRAY_A
        ) ?: [];

        // Get child row for standard/term context
        $child_row = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT standard, term FROM {$wpdb->prefix}noey_children WHERE child_id = %d",
                $child_id
            ),
            ARRAY_A
        );

        return [
            'type'    => 'per_exam',
            'student' => [
                'standard' => $child_row['standard'] ?? $session['standard'],
                'term'     => $child_row['term'] ?? $session['term'],
            ],
            'exam' => [
                'session_id'         => $session_id,
                'subject'            => $session['subject'],
                'difficulty'         => $session['difficulty'],
                'score'              => (int) $session['score'],
                'total'              => (int) $session['total'],
                'percentage'         => (float) $session['percentage'],
                'time_taken_seconds' => (int) $session['time_taken_seconds'],
                'completed_at'       => $session['completed_at'],
            ],
            'topics' => array_map( static fn( $t ) => [
                'topic'   => $t['topic'],
                'correct' => (int) $t['correct'],
                'total'   => (int) $t['total'],
                'pct'     => (float) $t['pct'],
            ], $breakdown ),
        ];
    }

    /**
     * Build the weekly digest payload for a given child and ISO week.
     */
    public static function build_weekly_payload( int $child_id, string $iso_week ): array|WP_Error {
        global $wpdb;

        // Parse ISO week to date range
        [ $year, $week ] = sscanf( $iso_week, '%d-W%d' );
        $week_start = new DateTime();
        $week_start->setISODate( $year, $week );
        $week_start->setTime( 0, 0, 0 );
        $week_end = clone $week_start;
        $week_end->modify( '+7 days' );

        $sessions = $wpdb->get_results(
            $wpdb->prepare(
                "SELECT * FROM {$wpdb->prefix}noey_exam_sessions
                 WHERE child_id = %d AND state = 'completed'
                 AND completed_at >= %s AND completed_at < %s",
                $child_id,
                $week_start->format( 'Y-m-d H:i:s' ),
                $week_end->format( 'Y-m-d H:i:s' )
            ),
            ARRAY_A
        ) ?: [];

        $child_row = $wpdb->get_row(
            $wpdb->prepare(
                "SELECT standard, term FROM {$wpdb->prefix}noey_children WHERE child_id = %d",
                $child_id
            ),
            ARRAY_A
        );

        if ( empty( $sessions ) ) {
            return [
                'type'    => 'weekly',
                'student' => [ 'standard' => $child_row['standard'] ?? '', 'term' => $child_row['term'] ?? '' ],
                'period'  => [
                    'week'             => $iso_week,
                    'exams_completed'  => 0,
                    'total_time_seconds' => 0,
                ],
                'overall'  => [ 'average_score_pct' => 0, 'trend' => 'insufficient_data' ],
                'subjects' => [],
            ];
        }

        $exams_completed  = count( $sessions );
        $total_time       = array_sum( array_column( $sessions, 'time_taken_seconds' ) );
        $average_pct      = round( array_sum( array_column( $sessions, 'percentage' ) ) / $exams_completed, 1 );

        // Trend: compare with previous week
        $prev_week_start = clone $week_start;
        $prev_week_start->modify( '-7 days' );

        $prev_avg = $wpdb->get_var(
            $wpdb->prepare(
                "SELECT AVG(percentage) FROM {$wpdb->prefix}noey_exam_sessions
                 WHERE child_id = %d AND state = 'completed'
                 AND completed_at >= %s AND completed_at < %s",
                $child_id,
                $prev_week_start->format( 'Y-m-d H:i:s' ),
                $week_start->format( 'Y-m-d H:i:s' )
            )
        );

        $trend = 'stable';
        if ( $prev_avg !== null ) {
            $diff  = $average_pct - (float) $prev_avg;
            $trend = $diff >= 5 ? 'improving' : ( $diff <= -5 ? 'declining' : 'stable' );
        }

        // Subject aggregation
        $session_ids      = array_column( $sessions, 'session_id' );
        $placeholders     = implode( ',', array_fill( 0, count( $session_ids ), '%d' ) );

        $breakdowns = $wpdb->get_results(
            $wpdb->prepare(
                // phpcs:ignore
                "SELECT tb.topic, s.subject,
                        SUM(tb.correct) as correct,
                        SUM(tb.total)   as total
                 FROM {$wpdb->prefix}noey_topic_breakdown tb
                 JOIN {$wpdb->prefix}noey_exam_sessions s ON s.session_id = tb.session_id
                 WHERE tb.session_id IN ({$placeholders})
                 GROUP BY s.subject, tb.topic",
                ...$session_ids
            ),
            ARRAY_A
        ) ?: [];

        // Group by subject
        $subjects_map = [];
        foreach ( $sessions as $sess ) {
            $subj = $sess['subject'];
            if ( ! isset( $subjects_map[ $subj ] ) ) {
                $subjects_map[ $subj ] = [ 'exams' => 0, 'pct_sum' => 0, 'topics' => [] ];
            }
            $subjects_map[ $subj ]['exams']++;
            $subjects_map[ $subj ]['pct_sum'] += (float) $sess['percentage'];
        }

        foreach ( $breakdowns as $b ) {
            $pct = $b['total'] > 0 ? round( ( $b['correct'] / $b['total'] ) * 100, 1 ) : 0;
            $subjects_map[ $b['subject'] ]['topics'][] = [
                'topic'   => $b['topic'],
                'correct' => (int) $b['correct'],
                'total'   => (int) $b['total'],
                'pct'     => $pct,
            ];
        }

        $subjects = [];
        foreach ( $subjects_map as $name => $data ) {
            $subjects[] = [
                'subject'     => $name,
                'exams'       => $data['exams'],
                'average_pct' => round( $data['pct_sum'] / $data['exams'], 1 ),
                'topics'      => $data['topics'],
            ];
        }

        return [
            'type'    => 'weekly',
            'student' => [
                'standard' => $child_row['standard'] ?? '',
                'term'     => $child_row['term'] ?? '',
            ],
            'period' => [
                'week'               => $iso_week,
                'exams_completed'    => $exams_completed,
                'total_time_seconds' => (int) $total_time,
            ],
            'overall' => [
                'average_score_pct' => $average_pct,
                'trend'             => $trend,
            ],
            'subjects' => $subjects,
        ];
    }

    // ── Railway Calls ─────────────────────────────────────────────────────────

    /**
     * Call Railway POST /insight for a per-exam coaching note.
     *
     * Railway payload: { user_id, standard, subject, topic_breakdown[] }
     * topic_breakdown item: { topic, correct, total, percentage }
     */
    private static function call_railway_exam_insight( array $payload ): array|WP_Error {
        $endpoint = rtrim( get_option( 'noey_railway_endpoint', '' ), '/' );
        $api_key  = get_option( 'noey_railway_api_key', '' );

        if ( ! $endpoint ) {
            return new WP_Error( 'noey_railway_not_configured', 'AI insight endpoint not configured.', [ 'status' => 503 ] );
        }

        // Build Railway-compatible per-exam payload
        $railway_payload = [
            'user_id'         => (string) ( $payload['exam']['session_id'] ?? 'session' ),
            'standard'        => $payload['student']['standard'] ?? '',
            'subject'         => Noey_Exam_Service::normalise_subject( $payload['exam']['subject'] ?? '' ),
            'topic_breakdown' => array_map( static fn( $t ) => [
                'topic'      => $t['topic'],
                'correct'    => (int) $t['correct'],
                'total'      => (int) $t['total'],
                'percentage' => (float) $t['pct'],
            ], $payload['topics'] ?? [] ),
        ];

        Noey_Debug::log( 'insight.railway', 'Calling Railway /insight', [
            'subject'       => $railway_payload['subject'],
            'topic_count'   => count( $railway_payload['topic_breakdown'] ),
        ], null, 'info' );

        return self::post_to_railway( '/insight', $railway_payload, $api_key );
    }

    /**
     * Call Railway POST /overall-insight/:user_id for weekly digest.
     *
     * Railway payload matches the weekly format exactly from the reference doc.
     */
    private static function call_railway_weekly_insight( int $child_id, array $payload ): array|WP_Error {
        $endpoint = rtrim( get_option( 'noey_railway_endpoint', '' ), '/' );
        $api_key  = get_option( 'noey_railway_api_key', '' );

        if ( ! $endpoint ) {
            return new WP_Error( 'noey_railway_not_configured', 'AI insight endpoint not configured.', [ 'status' => 503 ] );
        }

        Noey_Debug::log( 'insight.railway', 'Calling Railway /overall-insight', [
            'child_id' => $child_id,
            'iso_week' => $payload['period']['week'] ?? '',
            'exams'    => $payload['period']['exams_completed'] ?? 0,
        ], $child_id, 'info' );

        return self::post_to_railway( "/overall-insight/{$child_id}", $payload, $api_key );
    }

    private static function post_to_railway( string $path, array $body, string $api_key ): array|WP_Error {
        $endpoint = rtrim( get_option( 'noey_railway_endpoint', '' ), '/' );

        $response = wp_remote_post( "{$endpoint}{$path}", [
            'timeout' => 45,
            'headers' => [
                'Authorization' => "Bearer {$api_key}",
                'Content-Type'  => 'application/json',
            ],
            'body' => wp_json_encode( $body ),
        ] );

        if ( is_wp_error( $response ) ) {
            Noey_Debug::log( 'insight.railway', 'Railway HTTP error', [
                'path'  => $path,
                'error' => $response->get_error_message(),
            ], null, 'error' );
            return new WP_Error( 'noey_railway_error', 'Failed to connect to AI insight service.', [ 'status' => 503 ] );
        }

        $code = wp_remote_retrieve_response_code( $response );
        $body_decoded = json_decode( wp_remote_retrieve_body( $response ), true );

        if ( $code !== 200 || empty( $body_decoded ) ) {
            Noey_Debug::log( 'insight.railway', 'Railway bad response', [
                'path'      => $path,
                'http_code' => $code,
                'body'      => $body_decoded,
            ], null, 'error' );
            return new WP_Error( 'noey_railway_error', 'AI insight service returned an error.', [ 'status' => 503 ] );
        }

        Noey_Debug::log( 'insight.railway', 'Insight received', [
            'path'   => $path,
            'length' => strlen( $body_decoded['insight'] ?? '' ),
        ], null, 'info' );

        return $body_decoded;
    }
}
